language: dart
dart:
  - stable

addons:
  chrome: stable
  firefox: latest

before_install:
  - "npm i -g ganache-cli"

script: tool/build.sh
after_success: 'bash <(curl -s https://codecov.io/bash) -f lcov.info'