name: web3dart
description: Dart library to connect to Ethereum clients. Allows you to send transactions and build DApps in Dart.
version: 0.4.5
author: simolus3 <simolus3@gmail.com>
homepage: https://github.com/simolus3/web3dart

environment:
  sdk: ">=1.8.0 <3.0.0"

dependencies:
  pointycastle: ^1.0.1
  convert: ^2.1.1
  meta: ^1.1.7
  http: ^0.12.0
  tuple: ^1.0.2
  uuid: ^2.0.0
  isolate: ^2.0.0

dev_dependencies:
  test: ^1.5.3
  mockito: ^4.0.0