name: web3dart
description: Dart library to connect to Ethereum clients. Send transactions and interact with smart contracts!
version: 1.1.1+1
author: Simon Binder <oss@simonbinder.eu>
homepage: https://github.com/simolus3/web3dart

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  pointycastle: ^1.0.1
  convert: ^2.1.1
  meta: ^1.1.0
  http: ^0.12.0
  uuid: ^2.0.0
  isolate: ^2.0.0
  typed_data: ^1.1.6
  stream_channel: ^2.0.0
  json_rpc_2: ^2.1.0

dev_dependencies:
  web_socket_channel: ^1.0.0
  path: ^1.6.2
  test: ^1.5.3
  test_api: # _api and _core version will be determined by the test package
  test_core:
  mockito: ^4.0.0
  coverage: ^0.13.0

dependency_overrides:
  coverage:
    git: https://github.com/simolus3/coverage.git
