name: web3dart
description: Ethereum library, build DApps in Dart
version: 0.0.2
author: simolus3

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  pointycastle:
  jsonrpc2:

dev_dependencies:
  test: ^0.12.0
